//
// Autogenerated from java_tru using Queries.javaTR
// do not edit this file, look for Queries.javaTR and change this
// or you may loose all your changes and probably choose the wrong method.
// goto http://www.strux.net to find more information.
//
// based on Queries.javaTR , version : 3.0
//****************************************
// expect the following output (after run of createDemoDb.sql)
//****************************************
// Fields of T1
//   id               : 1
//     Character fields:
//       VARCHAR2_field1  : 'a'
//       VARCHAR2_field2  : 'abc????'
//       VARCHAR2_field3  : 'ABC????'
//       NVARCHAR2_field1 : 'b'
//       NVARCHAR2_field2 : 'cde???'
//       NVARCHAR2_field3 : 'CDE???'
//       CHAR_field1      : 'c'
//       CHAR_field2      : 'efg???    '
//       CHAR_field3      : 'EFG???    '
//       NCHAR_field1     : 'd'
//       NCHAR_field2     : 'e'
//       NCHAR_field3     : 'HIJ???    '
//     Number fields:
//       NUMBER_field1    : 1
//       NUMBER_field2    : 2
//       NUMBER_field3    : 3
//       NUMBER_field4    : 5
//     Date fields:
//       TIMESTAMP_field1 : 2098-12-25.17.30. 0. 0
//       TIMESTAMP_field2 : null
//   accessing table T2
//   status        : true
//   f2            : 'eins'
//   
// Fields of T1
//   id               : 2
//     Character fields:
//       VARCHAR2_field1  : ' '
//       VARCHAR2_field2  : 'null'
//       VARCHAR2_field3  : 'null'
//       NVARCHAR2_field1 : 'null'
//       NVARCHAR2_field2 : 'null'
//       NVARCHAR2_field3 : 'null'
//       CHAR_field1      : ' '
//       CHAR_field2      : 'null'
//       CHAR_field3      : 'null'
//       NCHAR_field1     : ' '
//       NCHAR_field2     : 'null'
//       NCHAR_field3     : 'null'
//     Number fields:
//       NUMBER_field1    : 0
//       NUMBER_field2    : null
//       NUMBER_field3    : 0
//       NUMBER_field4    : 0
//     Date fields:
//       TIMESTAMP_field1 : null
//       TIMESTAMP_field2 : null
//   accessing table T2
//   status        : true
//   f2            : 'one'
//   
// Fields of T1
//   id               : 3
//     Character fields:
//       VARCHAR2_field1  : 'a'
//       VARCHAR2_field2  : 'abcdefghij'
//       VARCHAR2_field3  : 'abcdefghij'
//       NVARCHAR2_field1 : 'a'
//       NVARCHAR2_field2 : 'abcdefghij'
//       NVARCHAR2_field3 : 'abcdefghij'
//       CHAR_field1      : 'a'
//       CHAR_field2      : 'abcdefghij'
//       CHAR_field3      : 'abcdefghij'
//       NCHAR_field1     : 'a'
//       NCHAR_field2     : 'a'
//       NCHAR_field3     : 'abcdefghij'
//     Number fields:
//       NUMBER_field1    : 99999999999999
//       NUMBER_field2    : 9999999999
//       NUMBER_field3    : 999999
//       NUMBER_field4    : -8446744073709551617
//     Date fields:
//       TIMESTAMP_field1 : null
//       TIMESTAMP_field2 : null
//   accessing table T2
//   status        : false
//   f2            : ''
//****************************************
import java.sql.*;
import java.io.*;
import java.util.*;
import java.math.*;
public class Queries {
  public static void main(String argv[]) {
    if (argv.length == 1 && argv[0].equals("-version")) {
      System.out.println("version:");
      System.out.println("  Queries.javaTR	3.0");
      return;
    }
    System.out.println("running");
    try {
      test();
    } catch (SQLException ex) {
      System.out.println(""+ex);
    } catch (IOException ex) {
      System.out.println(""+ex);
    }
  }
  //****************************************
  // Holt eine Verbindung aus den Eigenschaften, die in
  // der Datei database.properties spezifiziert sind.
  // @return Die Datenbankverbindung
  //****************************************
  public static Connection getConnection() throws SQLException, IOException{
    Properties props = new Properties();
    FileInputStream in = new FileInputStream("database.properties");
    props.load(in);
    in.close();
    String drivers = props.getProperty("jdbc.drivers");
    if (drivers != null) {
      System.setProperty("jdbc.drivers", drivers);
    }
    String url = props.getProperty("jdbc.url");
    String username = props.getProperty("jdbc.username");
    String password = props.getProperty("jdbc.password");
    return DriverManager.getConnection(url, username, password);
  }
  static void test() throws SQLException, IOException{
    boolean status;
    long id = 0;
    char VARCHAR2_field1=' ';                      // VARCHAR2_field1        VARCHAR2(1)           
    String VARCHAR2_field2="";                     // VARCHAR2_field2        VARCHAR2(10 BYTE)     
    String VARCHAR2_field3="";                     // VARCHAR2_field3        VARCHAR2(10 CHAR)     
    String NVARCHAR2_field1="";                    // NVARCHAR2_field1       NVARCHAR2(1)  
    String NVARCHAR2_field2="";                    // NVARCHAR2_field2       NVARCHAR2(10) 
    String NVARCHAR2_field3="";                    // NVARCHAR2_field3       NVARCHAR2(10) 
    long NUMBER_field1=0;                          // NUMBER_field1          NUMBER                
    BigDecimal NUMBER_field2=null;                 // NUMBER_field2          NUMBER(10)            
    long NUMBER_field3=0;                          // NUMBER_field3          NUMBER(10,4)          
    long NUMBER_field4=0;                          // NUMBER_field4          NUMBER(19)
    //****************************************
    // LONG_field             LONG          
    //****************************************
    //****************************************
    // DATE_field             DATE          
    //****************************************
    //****************************************
    // BINARY_FLOAT_field     BINARY_FLOAT  
    //****************************************
    //****************************************
    // BINARY_DOUBLE_field    BINARY_DOUBLE 
    //****************************************
    String TIMESTAMP_field1="";                    // TIMESTAMP_field1       TIMESTAMP     
    String TIMESTAMP_field2="";                    // TIMESTAMP_field2       TIMESTAMP(9)  
    char CHAR_field1=' '       ;                   // CHAR_field1            CHAR(1)       
    String CHAR_field2="";                         // CHAR_field2            CHAR(10 BYTE) 
    String CHAR_field3="";                         // CHAR_field3            CHAR(10 CHAR) 
    char NCHAR_field1=' '      ;                   // NCHAR_field1           NCHAR         
    String NCHAR_field2="";                        // NCHAR_field2           NCHAR(1)      
    String NCHAR_field3="";                        // NCHAR_field3           NCHAR(10)     
    PreparedStatement stat1 = getConnection().prepareStatement(
       "SELECT "
        +" id"
        +" ,VARCHAR2_field1"
        +" ,VARCHAR2_field2"
        +" ,VARCHAR2_field3"
        +" ,NVARCHAR2_field1"
        +" ,NVARCHAR2_field2"
        +" ,NVARCHAR2_field3"
        +" ,NUMBER_field1"
        +" ,NUMBER_field2"
        +" ,NUMBER_field3"
        +" ,NUMBER_field4"
        +" ,TIMESTAMP_field1"
        +" ,TIMESTAMP_field2"
        +" ,CHAR_field1"
        +" ,CHAR_field2"
        +" ,CHAR_field3"
        +" ,NCHAR_field1"
        +" ,NCHAR_field2"
        +" ,NCHAR_field3"
        +" from t1"
        +" where"
          +" id < 4"
      );
      boolean status1;
      ResultSet rs1 = stat1.executeQuery();
      while (status1=rs1.next()) {
        if (status1) {
          id = rs1.getLong(1);	
          if (rs1.getString(2) != null) {
            VARCHAR2_field1 = rs1.getString(2).charAt(0);
          } else {
            VARCHAR2_field1 = ' ';
          }
          VARCHAR2_field2 = rs1.getString(3);	
          VARCHAR2_field3 = rs1.getString(4);	
          NVARCHAR2_field1 = rs1.getString(5);	
          NVARCHAR2_field2 = rs1.getString(6);	
          NVARCHAR2_field3 = rs1.getString(7);	
          NUMBER_field1 = rs1.getLong(8);	
          NUMBER_field2 = rs1.getBigDecimal(9);	
          NUMBER_field3 = rs1.getLong(10);	
          if (rs1.getBigDecimal(11) != null) {
            NUMBER_field4 = rs1.getBigDecimal(11).longValue();
          } else {
            NUMBER_field4 = 0;
          }
          TIMESTAMP_field1 = rs1.getString(12);	
          TIMESTAMP_field2 = rs1.getString(13);	
          if (rs1.getString(14) != null) {
            CHAR_field1 = rs1.getString(14).charAt(0);
          } else {
            CHAR_field1 = ' ';
          }
          CHAR_field2 = rs1.getString(15);	
          CHAR_field3 = rs1.getString(16);	
          if (rs1.getString(17) != null) {
            NCHAR_field1 = rs1.getString(17).charAt(0);
          } else {
            NCHAR_field1 = ' ';
          }
          NCHAR_field2 = rs1.getString(18);	
          NCHAR_field3 = rs1.getString(19);	
        }
        System.out.println("Fields of T1");
        System.out.println("  id               : "+id);
        System.out.println("    Character fields:");
        System.out.println("      VARCHAR2_field1  : '" + VARCHAR2_field1  + "'");
        System.out.println("      VARCHAR2_field2  : '" + VARCHAR2_field2  + "'");
        System.out.println("      VARCHAR2_field3  : '" + VARCHAR2_field3  + "'");
        System.out.println("      NVARCHAR2_field1 : '" + NVARCHAR2_field1 + "'");
        System.out.println("      NVARCHAR2_field2 : '" + NVARCHAR2_field2 + "'");
        System.out.println("      NVARCHAR2_field3 : '" + NVARCHAR2_field3 + "'");
        System.out.println("      CHAR_field1      : '" + CHAR_field1      + "'");
        System.out.println("      CHAR_field2      : '" + CHAR_field2      + "'");
        System.out.println("      CHAR_field3      : '" + CHAR_field3      + "'");
        System.out.println("      NCHAR_field1     : '" + NCHAR_field1     + "'");
        System.out.println("      NCHAR_field2     : '" + NCHAR_field2     + "'");
        System.out.println("      NCHAR_field3     : '" + NCHAR_field3     + "'");
        System.out.println("    Number fields:");
        System.out.println("      NUMBER_field1    : " + NUMBER_field1    );
        System.out.println("      NUMBER_field2    : " + NUMBER_field2    );
        System.out.println("      NUMBER_field3    : " + NUMBER_field3    );
        System.out.println("      NUMBER_field4    : " + NUMBER_field4    );
        System.out.println("    Date fields:");
        System.out.println("      TIMESTAMP_field1 : " + TIMESTAMP_field1 );
        System.out.println("      TIMESTAMP_field2 : " + TIMESTAMP_field2 );
        System.out.println("  accessing table T2");
        String f2="";                              // VARCHAR2_field2        VARCHAR2(10 BYTE)     
        PreparedStatement stat2 = getConnection().prepareStatement(
           "SELECT "
            +" VARCHAR2_field2"
            +" FROM t2"
            +" where"
              +" id = ?"
          );
          boolean status2;
          stat2.setLong(1,id);
          ResultSet rs2 = stat2.executeQuery();
          status2=rs2.next();
          if (status2) {
            f2 = rs2.getString(1);	
          }
          status=status2;
        stat2.close();
        System.out.println("  status        : "+status);
        System.out.println("  f2            : '" + f2  + "'");
        System.out.println("");
    }
    stat1.close();
  }
}
