//
// Autogenerated from java_tru using test.javaTR
// do not edit this file, look for test.javaTR and change this
// or you may loose all your changes and probably choose the wrong method.
// goto http://www.strux.net to find more information.
//
// based on test.javaTR , version : 3.0
package relativity;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;  //  a comment for this import
import com.borland.jbcl.layout.*;
import javax.swing.event.*;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
public class MainFrame extends JFrame {
  innerdoc() {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.innerdoc");
      }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    this is the main frame of the whole application
      one
      two
        two.one
    mt;                                            // vv
    author;                                        // hudini
  }
  {                                                // class constructor
    x.register(this);
    for (int i=0;i<x.length;i=i+1) {
      System.out.println("ok1");
    }
    for (i=0;i<x.length;i=i+1) {
      System.out.println("ok2");
    }
    for (i=0;i<x.length;i=i+1) {
      System.out.println("ok3");
    }
  }
  // vars
  JPanel contentPane;
  JMenuBar jMenuBar1              = new JMenuBar();
  JMenu jMenuFile                 = new JMenu();
  JMenuItem jMenuFileExit         = new JMenuItem();
  JMenu jMenuHelp                 = new JMenu();
  JMenuItem jMenuHelpAbout        = new JMenuItem();
  JToolBar jToolBar               = new JToolBar();
  JButton FileOpenButton          = new JButton();
  JButton FileCloseButton         = new JButton();
  JButton HelpButton              = new JButton();
  JPanel MainPanel                = new JPanel();
  XYLayout xYLayout1              = new XYLayout();
  JPanel Sliders                  = new JPanel();
  JPanel AnimationSpeed           = new JPanel();
  JLabel AnimationSpeedLabel      = new JLabel();
  JSlider AnimationSpeedSlider    = new JSlider();
  XYLayout xYLayout2              = new XYLayout();
  XYLayout xYLayout3              = new XYLayout();
  JLabel SpeedControlLabel        = new JLabel();
  XYLayout xYLayout4              = new XYLayout();
  JLabel RocketSpeedLabel         = new JLabel();
  JPanel RocketSpeed              = new JPanel();
  JSlider RocketSpeedSlider       = new JSlider();
  XYLayout xYLayout5              = new XYLayout();
  JLabel statusBar                = new JLabel();
  JTextField AnimationSpeedAsText = new JTextField();
  JTextField RocketSpeedAsText    = new JTextField();
  ether ether1                    = new ether();
  int OldRocketSpeed              = 0;
  ImageIcon image1;
  ImageIcon image2;
  ImageIcon image3;
  //// Hand written stuff	3
Timer animtimer = new Timer(10,new ActionListener() {
  public void actionPerformed(ActionEvent e) {
    ether1.incxy();
  }
});
  //// Resuming generated code
  // more native code
  //// Hand written stuff	3
  Timer xyz = new Timer(20,new ActionListener() {
    public void actionPerformed(ActionEvent e) {
      ether2.incxy();
    }
  });
  
  //// Resuming generated code
  //Construct the frame
  /**
  *  one
  *   two
  */
  public MainFrame() {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.MainFrame");
      }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    enableEvents(AWTEvent.WINDOW_EVENT_MASK);
    try {
      jbInit();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
  //Component initialization
  @Override
  private void jbInit() throws Exception{
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.jbInit");
      }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    image1 = new ImageIcon(relativity.MainFrame.class.getResource("openFile.png"));
    image2 = new ImageIcon(relativity.MainFrame.class.getResource("closeFile.png"));
    image3 = new ImageIcon(relativity.MainFrame.class.getResource("help.png"));
    contentPane = (JPanel) this.getContentPane();
    contentPane.setLayout(xYLayout5);
    this.setSize(new Dimension(800, 600));
    this.setTitle("Relativity");
    jMenuFile.setText("File");
    jMenuFileExit.setText("Exit");
    jMenuFileExit.addActionListener(new MainFrame_jMenuFileExit_ActionAdapter(this));
    jMenuHelp.setText("Help");
    jMenuHelpAbout.setText("About");
    jMenuHelpAbout.addActionListener(new MainFrame_jMenuHelpAbout_ActionAdapter(this));
    FileOpenButton.setIcon(image1);
    FileOpenButton.setToolTipText("Open File");
    FileCloseButton.setIcon(image2);
    FileCloseButton.setToolTipText("Close File");
    HelpButton.setIcon(image3);
    HelpButton.setToolTipText("Help");
    MainPanel.setLayout(xYLayout1);
    MainPanel.setBackground(Color.pink);
    MainPanel.setBorder(BorderFactory.createLoweredBevelBorder());
    AnimationSpeedLabel.setText("Animation Speed");
    Sliders.setLayout(xYLayout2);
    AnimationSpeed.setLayout(xYLayout3);
    SpeedControlLabel.setFont(new java.awt.Font("Dialog", 1, 14));
    SpeedControlLabel.setText("Speed Control");
    RocketSpeedLabel.setText("Rocket Speed");
    RocketSpeed.setLayout(xYLayout4);
    statusBar.setBorder(BorderFactory.createEtchedBorder());
    statusBar.setOpaque(true);
    statusBar.setText(" waiting for start");
    AnimationSpeedAsText.setText("50");
    AnimationSpeedAsText.addActionListener(new MainFrame_AnimationSpeedAsText_actionAdapter(this));
    AnimationSpeedSlider.addChangeListener(new MainFrame_AnimationSpeedSlider_changeAdapter(this));
    AnimationSpeedSlider.setMajorTickSpacing(10);
    AnimationSpeedSlider.setMaximum(1000);
    AnimationSpeedSlider.setValue(0);
    RocketSpeedSlider.setMajorTickSpacing(10);
    RocketSpeedSlider.setMinorTickSpacing(5);
    RocketSpeedSlider.setPaintLabels(false);
    RocketSpeedSlider.setPaintTicks(true);
    RocketSpeedSlider.setName("rs");
    RocketSpeedSlider.setValue(0);
    RocketSpeedSlider.addChangeListener(new MainFrame_RocketSpeedSlider_changeAdapter(this));
    RocketSpeedAsText.addActionListener(new MainFrame_RocketSpeedAsText_actionAdapter(this));
    RocketSpeedAsText.setText("50");
    RocketSpeedAsText.addActionListener(new MainFrame_RocketSpeedAsText_actionAdapter(this));
    ether1.setBackground(new Color(159, 255, 255));
    jToolBar.add(FileOpenButton);
    jToolBar.add(FileCloseButton);
    jToolBar.add(HelpButton);
    jMenuFile.add(jMenuFileExit);
    jMenuHelp.add(jMenuHelpAbout);
    jMenuBar1.add(jMenuFile);
    jMenuBar1.add(jMenuHelp);
    this.setJMenuBar(jMenuBar1);
    contentPane.add(jToolBar,new XYConstraints(0, 0, 800, -1));
    contentPane.add(MainPanel,new XYConstraints(0, 31, 802, 570));
    AnimationSpeed.add(AnimationSpeedLabel,new XYConstraints(3, 3, -1, -1));
    AnimationSpeed.add(AnimationSpeedSlider,new XYConstraints(119, 2, 588, -1));
    AnimationSpeed.add(AnimationSpeedAsText,new XYConstraints(715, 2, 58, -1));
    MainPanel.add(ether1,new XYConstraints(6, 2, 624, 390));
    Sliders.add(RocketSpeed,new XYConstraints(2, 58, 786, -1));
    MainPanel.add(statusBar,new XYConstraints(3, 494, 793, 23));
    RocketSpeed.add(RocketSpeedLabel,new XYConstraints(3, 3, -1, -1));
    RocketSpeed.add(RocketSpeedSlider,new XYConstraints(119, 2, 586, 36));
    RocketSpeed.add(RocketSpeedAsText,new XYConstraints(715, 0, 58, -1));
    MainPanel.add(Sliders,new XYConstraints(6, 394, 791, 102));
    Sliders.add(SpeedControlLabel,new XYConstraints(6, 7, 177, 20));
    Sliders.add(AnimationSpeed,new XYConstraints(2, 29, 786, -1));
  }
  //File | Exit action performed
  @ClassPreamble (
    author = "John Doe",
    date = "3/17/2002",
    currentRevision = 6,
    lastModified = "4/12/2004",
    lastModifiedBy = "Jane Doe",
    reviewers = {"Alice", "Bob", "Cindy"},         // Note array notation
  )
  public void jMenuFileExit_actionPerformed(ActionEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.jMenuFileExit_actionPerformed");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    System.exit(0);
  }
  //Help | About action performed
  public void jMenuHelpAbout_actionPerformed(ActionEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.jMenuHelpAbout_actionPerformed");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    MainFrame_AboutBox dlg = new MainFrame_AboutBox(this);
    Dimension dlgSize = dlg.getPreferredSize();
    Dimension frmSize = getSize();
    Point loc = getLocation();
    dlg.setLocation((frmSize.width - dlgSize.width) / 2 + loc.x, (frmSize.height - dlgSize.height) / 2 + loc.y);
    dlg.setModal(true);
    dlg.pack();
    dlg.show();
  }
  //Overridden so we can exit when window is closed
  protected void processWindowEvent(WindowEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.processWindowEvent");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    super.processWindowEvent(e);
    if (e.getID() == WindowEvent.WINDOW_CLOSING) {
      jMenuFileExit_actionPerformed(null);
    } else if (e.getID() == WindowEvent.WINDOW_xxx) {
      jMenuFileExit_actionPerformed(xxx);
    }
  }
  void AnimationSpeedSlider_stateChanged(ChangeEvent e) {
    super(this);
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.AnimationSpeedSlider_stateChanged");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    AnimationSpeedAsText.setText(""+AnimationSpeedSlider.getValue());
    if (AnimationSpeedSlider.getValue() == 0) {
      statusBar.setText("Animation stopped");
      animtimer.stop();
    } else {
      statusBar.setText("Animation started");
      animtimer.setDelay(1000-AnimationSpeedSlider.getValue());
      animtimer.start();
    }
  }
  void AnimationSpeedAsText_actionPerformed(ActionEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.AnimationSpeedAsText_actionPerformed");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    AnimationSpeedSlider.setValue(Integer.parseInt(AnimationSpeedAsText.getText()));
  }
  void RocketSpeedSlider_stateChanged(ChangeEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.RocketSpeedSlider_stateChanged");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    RocketSpeedAsText.setText(""+RocketSpeedSlider.getValue());
    if (RocketSpeedSlider.getValue() == 0) {
      statusBar.setText("Rocket stopped");
      OldRocketSpeed=0;
    } else {
      if (OldRocketSpeed == 0) {
        /**
        *  a deeper nested jdoc
        *    1
        *    2
        *    2.1
        *  @t1 v1
        *  @t2 v2
        *    more for t2
        */
        statusBar.setText("Rocket launched ");
        OldRocketSpeed = RocketSpeedSlider.getValue();
      }
    }
  }
  void selectDemo() {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.selectDemo");
      }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    PreparedStatement stat1 = connection.prepareStatement(
       "SELECT "
        +" f1"
        +" from tab1"
        +" where cond1"
      );
      boolean status1;
      ResultSet rs1 = stat1.executeQuery();
      status1=rs1.next();
      if (status1) {
        f1 = rs1.getSTRING(1);	
      }
    stat1.close();
    return f1;
  }
  void cursorDemo() {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.cursorDemo");
      }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    PreparedStatement stat2 = connection.prepareStatement(
       "SELECT "
        +" f1"
        +" from tab1"
        +" where cond1"
      );
      boolean status2;
      ResultSet rs2 = stat2.executeQuery();
      while (status2=rs2.next()) {
        if (status2) {
          f1 = rs2.getSTRING(1);	
        }
        if (f1.equals("none")) {
          rval=true;
          break;
        }
    }
    stat2.close();
    return rval;
  }
  /** doc in the jdoc-line mit Umlauten äöüÄÖÜß&
  *  and more to come mit Umlauten äöüÄÖÜß&
  */
  void RocketSpeedAsText_actionPerformed(ActionEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.RocketSpeedAsText_actionPerformed");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    RocketSpeedSlider.setValue(Integer.parseInt(RocketSpeedAsText.getText()));
  }
  foo(int a, boolean flag) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame.foo");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:a="+a);
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("2:flag="+flag);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    while (true) {
      bla();
    }
  }
}
/**
*  some docu
*   some more docu
*/
abstract class MainFrame_jMenuFileExit_ActionAdapter implements ActionListener {
  // vars
  MainFrame adaptee;
  /**
  *  here we have an apdaptor
  *    een
  *    twee
  *      twee.een
  *  @tag1 value1
  *  @tag2 value2
  *    more about value2
  *      eins
  *      zwei
  *        zwei.eins
  */
  MainFrame_jMenuFileExit_ActionAdapter(MainFrame adaptee) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_jMenuFileExit_ActionAdapter.MainFrame_jMenuFileExit_ActionAdapter");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:adaptee="+adaptee);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    this.adaptee = adaptee;
  }
  public void actionPerformed(ActionEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_jMenuFileExit_ActionAdapter.actionPerformed");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    adaptee.jMenuFileExit_actionPerformed(e);
  }
  /**
  *  doc for the abstract function
  */
  public abstract void adjust(int i);
}
class MainFrame_jMenuHelpAbout_ActionAdapter implements ActionListener {
  // vars
  MainFrame adaptee;
  MainFrame_jMenuHelpAbout_ActionAdapter(MainFrame adaptee) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_jMenuHelpAbout_ActionAdapter.MainFrame_jMenuHelpAbout_ActionAdapter");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:adaptee="+adaptee);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    this.adaptee = adaptee;
  }
  public void actionPerformed(ActionEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_jMenuHelpAbout_ActionAdapter.actionPerformed");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    adaptee.jMenuHelpAbout_actionPerformed(e);
  }
  /**
  *  docu for inner
  *  @author hudini
  */
  class inner {
  }
}
class MainFrame_AnimationSpeedSlider_changeAdapter implements javax.swing.event.ChangeListener {
  // vars
  MainFrame adaptee;
  /**
  *  docu for MainFrame_AnimationSpeedSlider_changeAdapter
  *   some more docu
  */
  MainFrame_AnimationSpeedSlider_changeAdapter(MainFrame adaptee) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_AnimationSpeedSlider_changeAdapter.MainFrame_AnimationSpeedSlider_changeAdapter");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:adaptee="+adaptee);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    this.adaptee = adaptee;
  }
  public void stateChanged(ChangeEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_AnimationSpeedSlider_changeAdapter.stateChanged");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    adaptee.AnimationSpeedSlider_stateChanged(e);
  }
}
class MainFrame_AnimationSpeedAsText_actionAdapter implements java.awt.event.ActionListener {
  // vars
  MainFrame adaptee;
  MainFrame_AnimationSpeedAsText_actionAdapter(MainFrame adaptee) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_AnimationSpeedAsText_actionAdapter.MainFrame_AnimationSpeedAsText_actionAdapter");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:adaptee="+adaptee);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    this.adaptee = adaptee;
  }
  public void actionPerformed(ActionEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_AnimationSpeedAsText_actionAdapter.actionPerformed");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    adaptee.AnimationSpeedAsText_actionPerformed(e);
  }
}
class MainFrame_RocketSpeedSlider_changeAdapter implements javax.swing.event.ChangeListener {
  // vars
  MainFrame adaptee;
  MainFrame_RocketSpeedSlider_changeAdapter(MainFrame adaptee) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_RocketSpeedSlider_changeAdapter.MainFrame_RocketSpeedSlider_changeAdapter");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:adaptee="+adaptee);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    this.adaptee = adaptee;
  }
  public void stateChanged(ChangeEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_RocketSpeedSlider_changeAdapter.stateChanged");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    adaptee.RocketSpeedSlider_stateChanged(e);
    for (int c : table.getSelectedRows()) {
      output.append(String.format(" %d", c));
    }
  }
}
class MainFrame_RocketSpeedAsText_actionAdapter implements java.awt.event.ActionListener {
  // vars
  MainFrame adaptee;
  MainFrame_RocketSpeedAsText_actionAdapter(MainFrame adaptee) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_RocketSpeedAsText_actionAdapter.MainFrame_RocketSpeedAsText_actionAdapter");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:adaptee="+adaptee);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    this.adaptee = adaptee;
  }
  public void actionPerformed(ActionEvent e) {
    { // generated for flow-trace-debugging
      boolean fullstack;
      if (System.getProperty("tru_deb","0").equals("1")) {
        StackTraceElement[] stea=(new Throwable()).getStackTrace();
        int l=stea.length;
      if (fullstack=(System.getProperty("tru_deb_fullstack","0").equals("1"))) {
        for (int j=0;j<l;j++) {
          for (int i=0;i<l;i++) System.err.print(" ");
          if (stea[j].isNativeMethod()) {
            System.err.print("!");
          } else {
            System.err.print("*");
          }
          System.err.println(stea[j]);
        }
      } else {
        for (int i=0;i<l;i++) System.err.print(" ");
        System.err.println("MainFrame_RocketSpeedAsText_actionAdapter.actionPerformed");
      }
        if (System.getProperty("tru_deb_args","0").equals("1")) {
          for (int i=0;i<=l;i++) System.err.print(" ");
          System.err.println("1:e="+e);
        }
        if (fullstack) {
          for (int i=0;i<l;i++) System.err.print(" ");
          System.err.println("-------");
        }
      }
    }
    synchronized(that) {
      adaptee.RocketSpeedAsText_actionPerformed(e);
    }
    synchronized(this) {
      try {
        wait();
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      }
    }
    // needed for menuBar to work
    // import
    //   org.jdesktop.application.Action
    //   org.jdesktop.application.Application
    JMenuBar menuBar = new JMenuBar();
    {
      JMenu fileMenu = new JMenu();
      menuBar.add(fileMenu);
      fileMenu.setName("fileMenu");
      {
        JMenuItem jMenuItem1 = new JMenuItem();
        fileMenu.add(jMenuItem1);
        jMenuItem1.setAction(Application.getInstance().getContext().getActionMap(this).get("newFile"));
      }
      {
        JMenuItem jMenuItem2 = new JMenuItem();
        fileMenu.add(jMenuItem2);
        jMenuItem2.setAction(Application.getInstance().getContext().getActionMap(this).get("open"));
      }
      {
        JMenuItem jMenuItem3 = new JMenuItem();
        fileMenu.add(jMenuItem3);
        jMenuItem3.setAction(Application.getInstance().getContext().getActionMap(this).get("save"));
      }
      {
        JMenuItem runMenuItem = new JMenuItem();
        runMenuItem.setName("runMenuItem");
        fileMenu.add(runMenuItem);
        runMenuItem.addActionListener(new ActionListener() {
                                          public void actionPerformed(ActionEvent evt) {
                                            runButtonActionPerformed(evt);
                                          }
                                        }
                                       );
      }
      {
        JMenuItem closeMenuItem = new JMenuItem();
        closeMenuItem.setName("closeMenuItem");
        fileMenu.add(closeMenuItem);
        closeMenuItem.addActionListener(new ActionListener() {
                                          public void actionPerformed(ActionEvent evt) {
                                            closeMenuItemActionPerformed(evt);
                                          }
                                        }
                                       );
      }
    }
    {
      JMenu editMenu = new JMenu();
      menuBar.add(editMenu);
      editMenu.setName("editMenu");
      {
        JMenuItem jMenuItem4 = new JMenuItem();
        editMenu.add(jMenuItem4);
        jMenuItem4.setAction(Application.getInstance().getContext().getActionMap(this).get("copy"));
      }
      {
        JMenuItem jMenuItem5 = new JMenuItem();
        editMenu.add(jMenuItem5);
        jMenuItem5.setAction(Application.getInstance().getContext().getActionMap(this).get("cut"));
      }
      {
        JMenuItem jMenuItem6 = new JMenuItem();
        editMenu.add(jMenuItem6);
        jMenuItem6.setAction(Application.getInstance().getContext().getActionMap(this).get("paste"));
      }
      {
        JMenuItem jMenuItem7 = new JMenuItem();
        editMenu.add(jMenuItem7);
        jMenuItem7.setAction(Application.getInstance().getContext().getActionMap(this).get("delete"));
      }
      {
        JMenuItem xMenu = new JMenuItem();
        xMenu.setName("xMenu");
        editMenu.add(xMenu);
        xMenu.addActionListener(new ActionListener() {
                                          public void actionPerformed(ActionEvent evt) {
                                            xMenu(evt);
                                          }
                                        }
                                       );
      }
    }
    getMainFrame().setJMenuBar(menuBar);
  }
}
