/*
* Autogenerated from c_tru using ctest.ccTR
* do not edit this file, look for ctest.ccTR and change this
* or you may loose all your changes and probably choose the wrong method.
* goto http://www.strux.net to find more information.
*/
#ifdef __cplusplus
extern "C" {
#endif
#if	HAVE_CONFIG_H
#include <config.h>
#endif
int opt_a = 0;
int opt_b = 0;
const char *opt_f = "/tmp/schrott";
int opt_t = 0;
// based on ctest.ccTR , version : 3.0
#include <iostream.h>
#include "ctest.h"
using std::string;
using std::regex;
// based on ctest.ccTR , version : 3.0a
/**
 * emit a usage to stderr and exit with code 1
 */
void usage()
{
  fputs("usage : ctest\n",stderr);
  fputs("this program only serves as a test-suite\n",stderr);
  fputs("it does *NOT* do anything use- or harmfull\n",stderr);
  fputs("It simply shows the possibilities\n",stderr);
  fputs(" You can have any indent here\n",stderr);
  fputs("  1\n",stderr);
  fputs("       2\n",stderr);
  fputs("      3\n",stderr);
  fputs("     4\n",stderr);
  fputs("	 6\n",stderr);
  fputs("         6\n",stderr);
  fputs("Tables look like this\n",stderr);
  fputs("1	2\n",stderr);
  fputs("11	22\n",stderr);
  fputs("111	222\n",stderr);
  fputs("1111	2222\n",stderr);
  fputs("11111	22222\n",stderr);
  fputs("111111	222222\n",stderr);
  fputs("1111111	2222222\n",stderr);
  fputs("\n",stderr);
  fputs("OPTIONS:\n",stderr);
  fputs("	-a	Option a\n",stderr);
  fputs("		description for option a\n",stderr);
  fputs("	-b	Option b\n",stderr);
  fputs("	-f=file	file name\n",stderr);
  fputs("		default for file is /tmp/schrott\n",stderr);
  fputs("		description for option f\n",stderr);
  fputs("	-t	Option t\n",stderr);
  fputs("	-version	show version information\n",stderr);
  exit(1);
}
/* types */
typedef int INT;                                  /* for portability */
typedef char CHAR;
/** a silly comment */
#define	  a		1 + 2
/** a silly comment */
#define	  aa		1 + 2
/** a silly comment */
#define	  aaa		1 + 2
/** a silly comment */
#define	  aaaa		1 + 2
/** a silly comment */
#define	  aaaaa		1 + 2
/** a silly comment */
#define	  aaaaaa	1 + 2
/** a silly comment */
#define	  aaaaaaa	1 + 2
/** a silly comment */
#define	  aaaaaaaa	1 + 2
/** a silly comment */
#define	  aaaaaaaaa	1 + 2
/** a silly comment */
#define	  aaaaaaaaaa	1 + 2
/** a silly comment */
#define	  aaaaaaaaaaa	1 + 2
/** a silly comment */
#define	  aaaaaaaaaaaa	1 + 2
#define	  bbbbbbbbbbbb	1 + 2
#define	Long	(l,\
o,\
n,\
 g)\
  
#define	  Text	"running"
char *varwithtextacrossmultiplelines = "pure c-code can be produced
  as you can see here
  You could not write such a thing as statement, since a ; would
  be appended to each line
  and tabs	wouldn't be as expected
  No such thing happens in this mode
  Empty lines will survive

  And :
    leading spaces will survive relative to c code
    But :
      leading tabs will be converted to lots of spaces";

/* vars */
enum colours {
  red,
  green,
  blue,
};
/** Test statement */
int i=0;
// a comment in the var-section
int j[] = {
  1,
  2,
  3,
};

int main(int argc,char **argv)
{
  if (argc == 2 && argv[1][0] == '-' &&
                   argv[1][1] == 'v' &&
                   argv[1][2] == 'e' &&
                   argv[1][3] == 'r' &&
                   argv[1][4] == 's' &&
                   argv[1][5] == 'i' &&
                   argv[1][6] == 'o' &&
                   argv[1][7] == 'n' &&
                   argv[1][8] == '\0') {
    printf("Version :\n");
    printf("  ctest.ccTR\t3.0\n");
    printf("  ctest.ccTR\t3.0a\n");
    return 0;
  }
  if (argc == 2 && argv[1][0] == '-' && argv[1][1] == '?' && argv[1][2] == '\0') {
    usage();
  }
  int a=17;                                        // a comment
  int b=0;
  char *c=0;
  cout << Text << endl;
  char optchar;
#include <getopt.h>
  while ((optchar=getopt(argc,argv,"tf:ba")) != EOF) {/* Test Option */
    /* -a : Option a */
    if (optchar == 'a') {
      opt_a++;
      a=1;
    }
    /* -b : Option b */
    if (optchar == 'b') {
      opt_b++;
      b=1;
      a=0;
    }
    /* -f : file name */
    if (optchar == 'f') {
      if (*optarg == '=') optarg++;
      opt_f = optarg;
    }
    /* -t : Option t */
    if (optchar == 't') {
      opt_t++;
      test(3,4);
    }
    if (optchar == '?') usage();
  }
  printf("-a\t" << opt_a << endl);                 // another comment
  printf("-b\t" << opt_b << endl);
  printf("-f\t" << opt_f << endl);
  printf("-c\t" << opt_c << endl);
  printf("-t\t" << opt_t << endl);
  cout << "optind is " << getopt.optind << endl;
#if	1
  if (!(1==1)) {
    cerr << "PANIC, PANIC, PANIC";
  } else {
    cout << "42";
  }
  if (0) {
  }
  if (1) {
    i=0;
  } else {
    i=1;
  }
  if (2) {
    i=2;
  } else if (b) {
    // Test if
    int k = 4;
    for (i=0;i<3;i++) {
      // Test for
      int j = i*i;
      cout << i << " : " << j << endl;
    }
    while (i--) {
      // Test while
      while (k--) {
        cout << k << endl;
      }
    }
    if (x1) {
      y(1);
    } else if (!(x2)) {
      y(2);
    } else {
      y(3);
    }
  } else {
    // Test else
    cout << "you did not give me a b" << endl;
  }
#endif
  a=0;
  do {
    cout << a++;
    if (a< 2) {
      cout << " smaller 2" << endl;
    } else if (a== 2) {
      cout << " equal 2" << endl;
    } else if (a> 2) {
      cout << " greater 2" << endl;
    } else {
      cout << " cannot occur" << endl;
    }
  } while (!(a>5));
  if (a== 6) {
    cout << a << " equal 6" << endl;
  }
  if (a>  5) {
    cout << a << " greater 5" << endl;
  }
  if (a<  2) {
    cout << a << " smaller 2" << endl;
  }
  xay
  1a2
    3a4
      5a6
    7a8a9
    // copied unchanged
    
  xby
  1b2
    3b4
      5b6
    7b8b9
    // copied unchanged
    
  xcy
  1c2
    3c4
      5c6
    7c8c9
    // copied unchanged
    
  xay
  a1a2
    3a4
    
  xby
  b1b2
    3b4
    
  xcy
  c1c2
    3c4
    
}
/**
*  a short description for function test.
*  A detailed description for test.
*  @param f a description for param f
*  @param g a description for param g
*  @return a description for the return value
*/

void test(int f, int g) interrupt INT19
{
  cout << "called test()" << endl;
  switch (f) {                                    /* Test switch */
    default :                                     /* Test default for switch */
    {
      cout << "internal" << endl;
      /* no break */
    }
    case 1 :
    case 2 :
    {
      if (wa) {
      } else {
        b;
      }
      break;
    }
    case 3 :                                      /* Test case for switch */
    {
      cout << "I feel good" << endl;
      switch (g) {
        case 'a' :
        {
          cout << "xingalf";
          /* no break */
        }
        case 'b' :
        {
          cout << "kringalf";
          break;
        }
      }
      break;
    }
    case 4 :
    {
      cout << "Me too" << endl;
      switch (f) {
        case 'a' :
        {
          cout << "knusel";
        }
        case 'b' :
        {
          cout << "wusel";
        }
        default :
        {
          cout << "drusel";
        }
      }
      break;
    }
  }
}

void nevercalled()
{
  /*****************************************
  * this function is never called
  ***************************************
  * because none of these functions is ever called
  *****************************************/
  while (1) {
    cerr << "kill me, kill me please" << endl;
  }
  while (1) {
    cerr << "I'm still alive, I wanna die" << endl;
  }
  for (int n : {0,1,2,3,4,5}) {
    std::cout << n << ' ';
  }
}
#ifdef __cplusplus
}
#endif
