c_tru_test: ctest4.c File Reference
ctest4.c File Reference
#include <iostream.h>
#include "ctest.h"
Macros
#define a 1 + 2
a silly comment
#define aa 1 + 2
a silly comment
#define aaa 1 + 2
a silly comment
#define aaaa 1 + 2
a silly comment
#define aaaaa 1 + 2
a silly comment
#define aaaaaa 1 + 2
a silly comment
#define aaaaaaa 1 + 2
a silly comment
#define aaaaaaaa 1 + 2
a silly comment
#define aaaaaaaaa 1 + 2
a silly comment
#define aaaaaaaaaa 1 + 2
a silly comment
#define aaaaaaaaaaa 1 + 2
a silly comment
#define aaaaaaaaaaaa 1 + 2
a silly comment
#define bbbbbbbbbbbb 1 + 2
#define Long
#define Text "running"
Typedefs
typedef int INT
typedef char CHAR
Enumerations
Functions
void usage ()
emit a usage to stderr and exit with code 1
int main (int argc, char **argv)
void test (int f, int g) interrupt INT19
a short description for function test.
void nevercalled ()
Variables
int opt_a = 0
int opt_b = 0
const char * opt_f = "/tmp/schrott"
int opt_t = 0
char * varwithtextacrossmultiplelines
int i =0
Test statement.
int j []
Macro Definition Documentation
#define a 1 + 2
a silly comment
Definition at line 59 of file ctest4.c.
Referenced by main().
#define aa 1 + 2
a silly comment
Definition at line 61 of file ctest4.c.
#define aaa 1 + 2
a silly comment
Definition at line 63 of file ctest4.c.
#define aaaa 1 + 2
a silly comment
Definition at line 65 of file ctest4.c.
#define aaaaa 1 + 2
a silly comment
Definition at line 67 of file ctest4.c.
#define aaaaaa 1 + 2
a silly comment
Definition at line 69 of file ctest4.c.
#define aaaaaaa 1 + 2
a silly comment
Definition at line 71 of file ctest4.c.
#define aaaaaaaa 1 + 2
a silly comment
Definition at line 73 of file ctest4.c.
#define aaaaaaaaa 1 + 2
a silly comment
Definition at line 75 of file ctest4.c.
#define aaaaaaaaaa 1 + 2
a silly comment
Definition at line 77 of file ctest4.c.
#define aaaaaaaaaaa 1 + 2
a silly comment
Definition at line 79 of file ctest4.c.
#define aaaaaaaaaaaa 1 + 2
a silly comment
Definition at line 81 of file ctest4.c.
#define bbbbbbbbbbbb 1 + 2
Definition at line 82 of file ctest4.c.
#define Long
Value:
(l,\
o,\
n,\
 g)\
Definition at line 83 of file ctest4.c.
#define Text "running"
Definition at line 88 of file ctest4.c.
Referenced by main().
Typedef Documentation
typedef char CHAR
Definition at line 57 of file ctest4.c.
typedef int INT
Definition at line 56 of file ctest4.c.
Enumeration Type Documentation
enum colours
Enumerator
red
green
blue
Definition at line 103 of file ctest4.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 117 of file ctest4.c.
References a, i, test(), Text, and usage().
void nevercalled ()
Definition at line 333 of file ctest4.c.
void test (int f, int g)
a short description for function test.
A detailed description for test.
Parameters
f a description for param f
g a description for param g
Returns
a description for the return value
Definition at line 276 of file ctest4.c.
Referenced by main().
void usage ()
emit a usage to stderr and exit with code 1
Definition at line 22 of file ctest4.c.
Referenced by main().
Variable Documentation
int i =0
Test statement.
Definition at line 109 of file ctest4.c.
Referenced by main().
int j[]
Initial value:
= {
  1,
  2,
  3,
}
Definition at line 111 of file ctest4.c.
int opt_a = 0
Definition at line 9 of file ctest4.c.
int opt_b = 0
Definition at line 10 of file ctest4.c.
const char* opt_f = "/tmp/schrott"
Definition at line 11 of file ctest4.c.
int opt_t = 0
Definition at line 12 of file ctest4.c.
char* varwithtextacrossmultiplelines
Initial value:
= "pure c-code can be produced
  as you can see here
  You could not write such a thing as statement, since a ; would
  be appended to each line
  and tabs      wouldn't be as expected
  No such thing happens in this mode
  Empty lines will survive
  And :
    leading spaces will survive relative to c code
    But :
      leading tabs will be converted to lots of spaces"
Definition at line 89 of file ctest4.c.